"""
dashboard/components/event_log.py
===================================
Live system-event console for APEX LKA.

Events are stored in st.session_state and accumulated across Streamlit reruns.
All events are real — generated by actual pipeline outcomes, never hardcoded.

Usage
-----
    from dashboard.components.event_log import add_event, render_event_log, EventType

    add_event(EventType.LANE_DETECTED, "Both lanes detected  [conf: 0.87]")
    render_event_log()
"""

import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import List

import streamlit as st


# ═══════════════════════════════════════════════════════════════════════════
# Event types
# ═══════════════════════════════════════════════════════════════════════════

class EventType(Enum):
    SYSTEM       = "SYS"
    CAMERA       = "CAM"
    MODEL        = "MDL"
    LANE_OK      = "OK "
    LANE_PARTIAL = "PRT"
    LANE_LOST    = "ERR"
    INFERENCE    = "INF"
    LOW_CONF     = "LOW"
    ERROR        = "ERR"
    INFO         = "INF"


# Colour per event type (CSS class suffix)
_EVENT_COLOR = {
    EventType.SYSTEM:       "sys",
    EventType.CAMERA:       "info",
    EventType.MODEL:        "info",
    EventType.LANE_OK:      "ok",
    EventType.LANE_PARTIAL: "warn",
    EventType.LANE_LOST:    "err",
    EventType.INFERENCE:    "info",
    EventType.LOW_CONF:     "warn",
    EventType.ERROR:        "err",
    EventType.INFO:         "info",
}

_MAX_EVENTS = 80   # rolling window


# ═══════════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════════

def _ensure_log() -> None:
    if "apex_event_log" not in st.session_state:
        st.session_state.apex_event_log = []


def add_event(etype: EventType, message: str) -> None:
    """Append a real system event to the log."""
    _ensure_log()
    ts = time.strftime("%H:%M:%S")
    st.session_state.apex_event_log.append({
        "ts":      ts,
        "type":    etype,
        "message": message,
    })
    # Rolling window
    if len(st.session_state.apex_event_log) > _MAX_EVENTS:
        st.session_state.apex_event_log = (
            st.session_state.apex_event_log[-_MAX_EVENTS:]
        )


def clear_events() -> None:
    st.session_state.apex_event_log = []


def render_event_log(max_rows: int = 12) -> None:
    """
    Render the last max_rows events as an in-page console.
    Call this from the dashboard — it reads from session_state.
    """
    _ensure_log()
    events = st.session_state.apex_event_log
    if not events:
        st.markdown(
            '<div class="event-log-empty">NO EVENTS — WAITING FOR PIPELINE DATA</div>',
            unsafe_allow_html=True,
        )
        return

    # Show newest first
    shown = list(reversed(events))[:max_rows]

    rows_html = ""
    for ev in shown:
        color_cls = _EVENT_COLOR.get(ev["type"], "info")
        rows_html += (
            f'<div class="event-row">'
            f'<span class="event-ts">{ev["ts"]}</span>'
            f'<span class="event-tag event-{color_cls}">{ev["type"].value}</span>'
            f'<span class="event-msg">{ev["message"]}</span>'
            f'</div>'
        )

    st.markdown(
        f'<div class="event-log">{rows_html}</div>',
        unsafe_allow_html=True,
    )
